//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goeie dag.
        /// </summary>
        internal static string Afrikaans {
            get {
                return ResourceManager.GetString("Afrikaans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tungjatjeta.
        /// </summary>
        internal static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahlan bik.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pryvitanne.
        /// </summary>
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomoskar.
        /// </summary>
        internal static string Bengali {
            get {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selam.
        /// </summary>
        internal static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingala ba.
        /// </summary>
        internal static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nín hao.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravo.
        /// </summary>
        internal static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazdar.
        /// </summary>
        internal static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helo.
        /// </summary>
        internal static string Filipino {
            get {
                return ResourceManager.GetString("Filipino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei.
        /// </summary>
        internal static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guten Tag.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geia!.
        /// </summary>
        internal static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shalóm.
        /// </summary>
        internal static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namasté.
        /// </summary>
        internal static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szia.
        /// </summary>
        internal static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai.
        /// </summary>
        internal static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiana.
        /// </summary>
        internal static string Iñupiaq {
            get {
                return ResourceManager.GetString("Iñupiaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia is muire dhuit.
        /// </summary>
        internal static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buongiorno.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kónnichi wa.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annyeonghaseyo.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabai dii.
        /// </summary>
        internal static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ave.
        /// </summary>
        internal static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es mīlu tevi.
        /// </summary>
        internal static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selamat petang.
        /// </summary>
        internal static string Malay {
            get {
                return ResourceManager.GetString("Malay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sain baina uu.
        /// </summary>
        internal static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namaste.
        /// </summary>
        internal static string Nepali {
            get {
                return ResourceManager.GetString("Nepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string Norwegian {
            get {
                return ResourceManager.GetString("Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salâm.
        /// </summary>
        internal static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witajcie.
        /// </summary>
        internal static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salut.
        /// </summary>
        internal static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privét.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talofa.
        /// </summary>
        internal static string Samoan {
            get {
                return ResourceManager.GetString("Samoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ćao.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazdar.
        /// </summary>
        internal static string Slovak {
            get {
                return ResourceManager.GetString("Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravo.
        /// </summary>
        internal static string Slovene {
            get {
                return ResourceManager.GetString("Slovene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jambo.
        /// </summary>
        internal static string Swahili {
            get {
                return ResourceManager.GetString("Swahili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej.
        /// </summary>
        internal static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halo.
        /// </summary>
        internal static string Tagalog {
            get {
                return ResourceManager.GetString("Tagalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sàwàtdee kráp.
        /// </summary>
        internal static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pryvít.
        /// </summary>
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaab arz hai.
        /// </summary>
        internal static string Urdu {
            get {
                return ResourceManager.GetString("Urdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
